language: swift
osx_image: xcode10

branches:
  only:
  - master
  - development
  
before_install:
  - pod install
  
script:
- xcodebuild clean build test -workspace CurrencyConverter.xcworkspace -scheme CurrencyConverter -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'

after_success:
  - bash <(curl -s https://codecov.io/bash)
